# Generated by Django 5.1.6 on 2025-04-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_card_department_student2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student2',
            name='Card_number',
        ),
        migrations.AddField(
            model_name='student2',
            name='card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookmodule.card'),
        ),
        migrations.AlterField(
            model_name='student2',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmodule.department'),
        ),
        migrations.AddField(
            model_name='student2',
            name='courses',
            field=models.ManyToManyField(to='bookmodule.course'),
        ),
    ]
